### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by zhanfeng0102** [chenyinkai/cykspace-node#7]
npm run dev

> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cykspace@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cykspace@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by chenyinkai** [comment]
@zhanfeng0102 重新拉下代码，或者你把 `webpack-dev-server` 的版本降到2版本。是因为 `webpack` 和 `webpack-dev-server` 版本不匹配引起的错误.
